### ISSUE TITLE
请求多次后，后面的请求会变的非常缓慢

### ISSUE THREAD

**Issue by Yunmeng97** [Next-DAO/atomicals-electrumx-proxy-docker#1]
![3252](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/151240985/9385b7d1-755c-477c-b557-e5989c34bd85)
这是我的请求时间图，大概正常速度请求20次，就开始变的缓慢，要一段时间才能恢复正常的请求速度，我想知道如何避免这个问题，或者正常请求速度的次数能更多一些。
非常感谢您的解答！

**Comment by lucky2077** [comment]
https://github.com/atomicals/electrumx-proxy/blob/main/src/app.ts#L104 自己摸索下？🤣

**Comment by Yunmeng97** [comment]
通过你指引的源码文件修改部分代码后，问题得到了解决，非常感谢您的帮助！
