### ISSUE TITLE
Request failed with status code 500：`unknown method "XXXX"`

### ISSUE THREAD

**Issue by renmengkai** [Next-DAO/atomicals-electrumx-proxy-docker#10]
### **atomicals-js cli run commond：yarn cli mint-dft dmint --satsbyte 30**

**### health check：**
![1700964008265](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/31378513/0ec9472f-d064-4382-9050-b96113d9ee5e)

**### docker log：**

![1700964683791](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/31378513/c3158167-2ea9-4125-803f-1f56dbab2984)

![1700963641318](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/31378513/288ff622-5154-49ff-81c4-b3cb99f9bd2a)

```
2023-11-26 09:53:34 request 172.18.0.1 26163860 blockchain.atomicals.get_by_ticker { method: 'blockchain.atomicals.get_by_ticker' } {}
2023-11-26 09:53:34 Connected: electrumx:50001
2023-11-26 09:53:34 params [ 'dmint' ]
2023-11-26 09:53:34 request_error 172.18.0.1 26163860 blockchain.atomicals.get_by_ticker {
2023-11-26 09:53:34   code: -32601,
2023-11-26 09:53:34   message: 'unknown method "blockchain.atomicals.get_by_ticker"'
2023-11-26 09:53:34 }
2023-11-26 09:53:34 POST /proxy/blockchain.atomicals.get_by_ticker 500 29.835 ms - 97
2023-11-26 09:54:04 LAST_PING_TIME_EXPIRED_RESETTING_CONNECTION 1700915934616
2023-11-26 09:54:04 Presisted Connection to ElectrumX(electrumx:50001) Server Closed.
```

**### terminal log：**
```
walletPath ./wallets/wallet.json
Args { mint_ticker: 'dmint' }
Meta undefined
Ctx undefined
====================================================================
Mint Interactive FT (Decentralized)
====================================================================
Atomical type: FUNGIBLE (decentralized) [
  {
    name: 'args',
    contentType: 'object',
    data: { mint_ticker: 'dmint' }
  }
] dmint
Mint for ticker:  dmint
error  AxiosError: Request failed with status code 500
    at settle (I:\atomicals-js\node_modules\axios\dist\node\axios.cjs:1913:12)
    at IncomingMessage.handleStreamEnd (I:\atomicals-js\node_modules\axios\dist\node\axios.cjs:2995:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.5.1',
      'Content-Length': '20',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker',
    data: '{"params":["dmint"]}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '20',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 585,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 39,
        [Symbol(triggerId)]: 37
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /proxy/blockchain.atomicals.get_by_ticker HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.5.1\r\n' +
      'Content-Length: 20\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: localhost:8080\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/proxy/blockchain.atomicals.get_by_ticker',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 38,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 20,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Object [AxiosHeaders] {
      'content-security-policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'cross-origin-opener-policy': 'same-origin',
      'cross-origin-resource-policy': 'same-origin',
      'origin-agent-cluster': '?1',
      'referrer-policy': 'no-referrer',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      'access-control-allow-origin': '*',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '97',
      etag: 'W/"61-rpDBLPkhbv6ckTMrH33aHDhaplU"',
      date: 'Sun, 26 Nov 2023 01:53:34 GMT',
      connection: 'keep-alive',
      'keep-alive': 'timeout=5'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker',
      data: '{"params":["dmint"]}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '20',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'POST /proxy/blockchain.atomicals.get_by_ticker HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.5.1\r\n' +
        'Content-Length: 20\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:8080\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/proxy/blockchain.atomicals.get_by_ticker',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: {
      success: false,
      code: -32601,
      message: 'unknown method "blockchain.atomicals.get_by_ticker"'
    }
  }
}
{
  "success": false,
  "message": "AxiosError: Request failed with status code 500",
  "error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (I:\\atomicals-js\\node_modules\\axios\\dist\\node\\axios.cjs:1913:12)\n    at IncomingMessage.handleStreamEnd (I:\\atomicals-js\\node_modules\\axios\\dist\\node\\axios.cjs:2995:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.5.1",
        "Content-Length": "20",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "url": "http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker",
      "data": "{\"params\":[\"dmint\"]}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
  }
}
Done in 0.75s.
```

**Comment by lvan001** [comment]
same to me,help

**Comment by lizqlife** [comment]
same to me,help

**Comment by lizqlife** [comment]
same to me,help

**Comment by lizqlife** [comment]
same problem，help please

**Comment by lucky2077** [comment]
Sorry form this problem.

This was caused by a Dockerfile modified from official repositoy. I tried to use rocksdb as `DB_ENGINE` but seems failed now.

To resolve this problem:

1. run `docker-compose down` to stop all containers.
2. delete `electrumx-data` directory, and copy directory with same name extracted from the `magnet` downloaded zip files to the `docker-compose.yml` directory.
3. run `docker-compose pull`
4. run `docker-compose up -d`, waiting for abount 30 minutes.

If you resolved， plz tell others who met same problem.

Sorry again.

----------------

抱歉造成这个问题。

为了测试 rocksdb ，我使用了官方仓库中的 Dockerfile ，并进行修改，因此出现了bug。

解决方法：

1. 执行 `docker-compose down` , 关闭所有容器
2. 删除 `electrumx-data` 目录，并将用种子下载解压缩出来的同名目录拷贝到 `docker-compose.yml` 所在的目录
3. 执行 `docker-compose pull`
4. 执行 `docker-compose up -d` ，等大概 30 分钟

如果你解决了，请帮忙告诉遇到同样问题的朋友。

再次表示抱歉。

**Comment by lizqlife** [comment]
如果我删除了electrumx-data目录并重新启动，是否还需要同步大量的区块数据？因为种子下载的区块数据只到11月14日，谢谢。

**Comment by lizqlife** [comment]
你好 我按照解决方法重做后，electrumx容器报错如下：
2023-11-26 19:44:01 ERROR:electrumx:ElectrumX server terminated abnormally
2023-11-26 19:44:01 Traceback (most recent call last):
2023-11-26 19:44:01   File "/electrumx/electrumx_server", line 35, in main
2023-11-26 19:44:01     asyncio.run(controller.run())
2023-11-26 19:44:01   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2023-11-26 19:44:01     return loop.run_until_complete(main)
2023-11-26 19:44:01   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2023-11-26 19:44:01   File "/electrumx/electrumx/lib/server_base.py", line 129, in run
2023-11-26 19:44:01     await server_task
2023-11-26 19:44:01   File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
2023-11-26 19:44:01     await self.serve(shutdown_event)
2023-11-26 19:44:01   File "/electrumx/electrumx/server/controller.py", line 137, in serve
2023-11-26 19:44:01     await group.spawn(wait_for_catchup())
2023-11-26 19:44:01   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
2023-11-26 19:44:01     await self.join()
2023-11-26 19:44:01   File "/electrumx/electrumx/lib/util.py", line 370, in join
2023-11-26 19:44:01     task.result()
2023-11-26 19:44:01   File "/electrumx/electrumx/server/block_processor.py", line 3399, in fetch_and_process_blocks
2023-11-26 19:44:01     await self._first_open_dbs()
2023-11-26 19:44:01   File "/electrumx/electrumx/server/block_processor.py", line 3378, in _first_open_dbs
2023-11-26 19:44:01     await self.db.open_for_sync()
2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 360, in open_for_sync
2023-11-26 19:44:01     await self._open_dbs(True, False)
2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 334, in _open_dbs
2023-11-26 19:44:01     self.read_utxo_state()
2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 971, in read_utxo_state
2023-11-26 19:44:01     self.db_atomical_count = state['atomical_count']
2023-11-26 19:44:01 KeyError: 'atomical_count'

**Comment by lucky2077** [comment]
> 你好 我按照解决方法重做后，electrumx容器报错如下：
> 
> 2023-11-26 19:44:01 ERROR:electrumx:ElectrumX server terminated abnormally
> 
> 2023-11-26 19:44:01 Traceback (most recent call last):
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx_server", line 35, in main
> 
> 2023-11-26 19:44:01     asyncio.run(controller.run())
> 
> 2023-11-26 19:44:01   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
> 
> 2023-11-26 19:44:01     return loop.run_until_complete(main)
> 
> 2023-11-26 19:44:01   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/lib/server_base.py", line 129, in run
> 
> 2023-11-26 19:44:01     await server_task
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
> 
> 2023-11-26 19:44:01     await self.serve(shutdown_event)
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/controller.py", line 137, in serve
> 
> 2023-11-26 19:44:01     await group.spawn(wait_for_catchup())
> 
> 2023-11-26 19:44:01   File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
> 
> 2023-11-26 19:44:01     await self.join()
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/lib/util.py", line 370, in join
> 
> 2023-11-26 19:44:01     task.result()
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/block_processor.py", line 3399, in fetch_and_process_blocks
> 
> 2023-11-26 19:44:01     await self._first_open_dbs()
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/block_processor.py", line 3378, in _first_open_dbs
> 
> 2023-11-26 19:44:01     await self.db.open_for_sync()
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 360, in open_for_sync
> 
> 2023-11-26 19:44:01     await self._open_dbs(True, False)
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 334, in _open_dbs
> 
> 2023-11-26 19:44:01     self.read_utxo_state()
> 
> 2023-11-26 19:44:01   File "/electrumx/electrumx/server/db.py", line 971, in read_utxo_state
> 
> 2023-11-26 19:44:01     self.db_atomical_count = state['atomical_count']
> 
> 2023-11-26 19:44:01 KeyError: 'atomical_count'

是不是没有重新 pull 镜像

**Comment by lizqlife** [comment]
重新pull了 我需要删除原有的镜像么？

**Comment by lucky2077** [comment]
索引目录有没有按步骤重新来

**Comment by lizqlife** [comment]
我们保存原有的数据吗？还是只能用11-14那个磁力下载的压缩包？

**Comment by lucky2077** [comment]
只能用压缩包，除非，你自己会每日备份数据，24日之前的应该可以用

**Comment by lizqlife** [comment]
好的，非常感谢您，我再去尝试下~！

**Comment by szhang67** [comment]
> 好的，非常感谢您，我再去尝试下~！

@lizqlife 你好，我也遇到了这个问题，请问你那边解决了吗？感谢！

**Comment by lizqlife** [comment]
> > 好的，非常感谢您，我再去尝试下~！
> 
> @lizqlife 你好，我也遇到了这个问题，请问你那边解决了吗？感谢！

已经解决了 按照官方的步骤来就可以，另外data数据可以通过磁力链接下载，然后在同步

**Comment by lk0pa** [comment]
现在我用最新的镜像和磁力链接下载的数据同步会出现上千个FailingStreak， Health的status 一直都没有变成健康的 ，请问是什么原因呢 @lucky2077

**Comment by truongbaophan** [comment]
为什么我从头同步数据时，exectrumx-data目录下不生成meta目录？报错如下
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/111491773/370e532d-e716-4eb2-be3e-fe332eba911c)

**Comment by lizqlife** [comment]
你好，我又遇到了新的问题，目前节点数据是同步正常的，但是使用私有节点的时候会报错。
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/27052073/33e13170-01e2-4cef-ac04-220ec28e91f6)


{
  "success": false,
  "message": "AxiosError: Request failed with status code 500",
  "error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (D:\\打新\\atom5\\atomicals-js-master\\node_modules\\axios\\dist\\node\\axios.cjs:1913:12)\n    at IncomingMessage.handleStreamEnd (D:\\打新\\atom5\\atomicals-js-master\\node_modules\\axios\\dist\\node\\axios.cjs:2995:11)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1368:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.5.1",
        "Content-Length": "18",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "url": "http://localhost:8080/proxy/blockchain.atomicals.get_by_ticker",
      "data": "{\"params\":[\"avm\"]}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
  }
}
Done in 10.50s.

**Comment by lucky2077** [comment]
是否已解决，猜测是当时avm还没部署好

**Comment by lizqlife** [comment]
> 是否已解决，猜测是当时avm还没部署好

没有解决，事实上我使用命令mint其它的铭文也是这样的报错，这是我刚才尝试的

**Comment by lizqlife** [comment]
![1701841748593](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/27052073/6d1beead-1940-43fd-b3ee-50ecad6d6de2)

**Comment by lucky2077** [comment]
如果换成官方 rpc 节点报错吗

**Comment by lizqlife** [comment]
> 如果换成官方 rpc 节点报错吗

官方节点可以运行 ，我给你截图，这里提示avm已经mint完毕。
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/27052073/94d93a93-fccf-4ee8-924f-0c025df08c4f)

**Comment by TinyLi** [comment]
@lucky2077 大佬，磁力链接如果用不了，同步速度也比较慢，有啥别的办法吗？能否提供一个新的下载链接，谢谢了
