### ISSUE TITLE
ERROR:Daemon:connection problem - check your daemon is running. Retrying occasionally... 

### ISSUE THREAD

**Issue by Alarical** [Next-DAO/atomicals-electrumx-proxy-docker#3]
最早tw上的docker方案会报这个错误，现在换成当前的配置方案，还是报这个error，请问是什么问题呢？

**Comment by hhfcvmars** [comment]
解决了吗？我也是报这个错误

**Comment by lucky2077** [comment]
麻烦提供一下，下列信息

1. btc 全节点的配置文件，rpc 用户名 密码请用 *** 替代
2. 当前的局域网 ip，例如 192.168.1.2
