### ISSUE TITLE
unhealthy 50001端口问题

### ISSUE THREAD

**Issue by HUHAOQIAN** [Next-DAO/atomicals-electrumx-proxy-docker#5]
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/30793630/2ae8abf4-8dac-429a-956c-f6bd6660979c)
应该已经同步好了
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/30793630/ee2d4487-add8-41a7-b572-68f0bfe32aef)
但是总是这样，求助

**Comment by GeekXtop** [comment]
跟你一样。搞半天都不行

**Comment by HUHAOQIAN** [comment]
自己好了。等等就行了。

**Comment by GeekXtop** [comment]
> 自己好了。等等就行了。

为啥我的不行，连续好几天都这样，已经同步到最新块
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/103322869/47c27e4f-8b54-4e7a-a1ce-da78e6899832)

**Comment by hhfcvmars** [comment]
> 自己好了。等等就行了。

需要同步完吗？还是等多久，我另外同步的服务是好的，就是检查一直提示这个

**Comment by hhfcvmars** [comment]
> 跟你一样。搞半天都不行

你的也好了吗？

**Comment by lucky2077** [comment]
猜测是 Windows 环境下，docker 使用的 wsl2，跨操作系统的磁盘性能太差，目前基本上遇到问题的都是 Windows

**Comment by ujsyehao** [comment]
老哥，我也一直提示unhealthy，怎么解决呢
