### ISSUE TITLE
ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...

### ISSUE THREAD

**Issue by hhfcvmars** [Next-DAO/atomicals-electrumx-proxy-docker#6]
Docker  运行起来一直提示如下错误

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/702a08f5-c2a0-417d-92c2-6f26170daa34)

以下是我的一些配置信息

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/b00a1057-f9ea-485f-9008-fa45656541a0)

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/fdae9753-ec33-46de-be31-bf1d96ef6e21)

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/7701810e-bca5-492a-97fa-f7aa8446ae58)

![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/62316749/15676d2b-3520-455a-946d-8ca0f75e5165)

**Comment by GeekXtop** [comment]
rpcuser和rpcpassword设置了就不需要设rpcauth了

**Comment by hhfcvmars** [comment]
> rpcuser和rpcpassword设置了就不需要设rpcauth了

这个感觉不是主要原因，我这注释掉rpcauth ，还是一样问题

**Comment by GhostBladeOne** [comment]
你可以试试 用rpc 访问一下看是否是ok.

**Comment by GeekXtop** [comment]
> > rpcuser和rpcpassword设置了就不需要设rpcauth了
> 
> 这个感觉不是主要原因，我这注释掉rpcauth ，还是一样问题

改成 test:123456@host.docker.internal:8332

**Comment by lucky2077** [comment]
btc 全节点配置文件再添加一个 rpcallowip=192.168.0.0/16 试试
