### ISSUE TITLE
下载文件放在哪里?

### ISSUE THREAD

**Issue by viponedream** [Next-DAO/atomicals-electrumx-proxy-docker#8]
magnet:?xt=urn:btih:7KW5OXSWUQ2EFF57URE42GBRL2XCN5AI&dn=ElectrumX-Data-20231114
下载了文件后放到哪?
我在目录下建立 /DB
然后把下载好的文件放到/DB/下面

![NW4)MW6( KFLBWOJ5%WQ1R2](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/16624529/b99f47ed-4d22-4c88-b885-bda9ddc8d7d1)

![F )$%LWK5NZR34A72FLG}EV](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/16624529/d25a8c90-3683-454e-a11b-2ededb7f923c)

**Comment by heroapn** [comment]
怎么解压

**Comment by lucky2077** [comment]
看上去你是用源码跑的，不知道看的哪个教程，可以参考下你看的教程的设置索引目录部分的说明

**Comment by lucky2077** [comment]
> 怎么解压

安装一下 7zip https://7-zip.org/
