### ISSUE TITLE
ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally...

### ISSUE THREAD

**Issue by xinzhongyouhai** [Next-DAO/atomicals-electrumx-proxy-docker#9]
这个问题找了好多解决
.env文件到底改哪个？
docker-compose.yml文件里的   environment:
      - DAEMON_URL=nextdao:nextdao@${IP:?}:8332
      - COIN=BitCoin
      - PEER_DISCOVERY=off
      - PEER_ANNOUNCE=""
      - MAX_SEND=3000000
      - 这一段DAEMON_URL=nextdao:nextdao@${IP:?}:8332  不需要修改吗？？？

**Comment by lizqlife** [comment]
我改成自己的bitcoin地址 也是报错。。。

**Comment by lucky2077** [comment]
麻烦提供一下，下列信息

1. btc 全节点的配置文件，rpc 用户名 密码请用 *** 替代
2. 当前的局域网 ip，例如 192.168.1.2

**Comment by lizqlife** [comment]
我已经解决了，我打开了bitcore的设置，然后重启bitcore就可以连上了。
![image](https://github.com/Next-DAO/atomicals-electrumx-proxy-docker/assets/27052073/e6491391-a78b-4234-be48-9e3d05ffe30f)

**Comment by lizqlife** [comment]
你好，两个服务都启动了，但是mint的是否报错如下： unknown method "blockchain.atomicals.get_by_ticker 请问怎么处理呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Next-DAO/atomicals-electrumx-proxy-docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月26日(星期天) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Next-DAO/atomicals-electrumx-proxy-docker] ERROR:Daemon:connection problem - check your daemon is running.  Retrying occasionally... (Issue #9)





 
麻烦提供一下，下列信息
  
btc 全节点的配置文件，rpc 用户名 密码请用 *** 替代
 
当前的局域网 ip，例如 192.168.1.2

**Comment by lucky2077** [comment]
> 这个问题找了好多解决 .env文件到底改哪个？ docker-compose.yml文件里的 environment: - DAEMON_URL=nextdao:nextdao@${IP:?}:8332 - COIN=BitCoin - PEER_DISCOVERY=off - PEER_ANNOUNCE="" - MAX_SEND=3000000 - 这一段DAEMON_URL=nextdao:nextdao@${IP:?}:8332 不需要修改吗？？？

按个库的步骤执行的话，不需要创建 .env ，把 `docker-compose.yml` 中的 DAEMON_URL 改对就行

**Comment by ujsyehao** [comment]
> 我已经解决了，我打开了bitcore的设置，然后重启bitcore就可以连上了。 ![image](https://private-user-images.githubusercontent.com/27052073/285635069-e6491391-a78b-4234-be48-9e3d05ffe30f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMTc1ODgsIm5iZiI6MTcwNDAxNzI4OCwicGF0aCI6Ii8yNzA1MjA3My8yODU2MzUwNjktZTY0OTEzOTEtYTc4Yi00MjM0LWJlNDgtOWUzZDA1ZmZlMzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDEwMDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNDdiOTNlN2Y1OWI2MmQ0ZTQ2YWEwZmI1MzU2MmQ5NmVlZTFhYzZiNDM1OTA5M2I4MjA2OGUxZTM1NTljMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9z4ZHJlXRKN1qd3GMxK9xans0Nm1YhwZPsHQp55uC6M)

你好，咋解决的呢
